servers:
  1:
    host: localhost
    raft_port: 5001
    http_port: 8001

    data_dir: "_data/1"
  2:
    host: localhost
    raft_port: 5002
    http_port: 8002

    data_dir: "_data/2"
  3:
    host: localhost
    raft_port: 5003
    http_port: 8003

    data_dir: "_data/3"
