{
 "title": "Generic",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "User space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(user_requests_count[$__rate_interval]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (endpoint) ((rate(user_requests_sum[$__rate_interval]) > 0) / (rate(user_requests_count[$__rate_interval]) > 0))",
     "legendFormat": "{{endpoint}} avg"
    },
    {
     "expr": "sum by (endpoint, quantile) (user_requests > 0)",
     "legendFormat": "{{endpoint}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Raft transport",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(raft_transport_message_size_sum[$__rate_interval]) / rate(raft_transport_message_size_count[$__rate_interval])",
       "legendFormat": "{{job}} avg"
      },
      { "expr": "raft_transport_message_size", "legendFormat": "{{job}} {{quantile}}" }
     ]
    },
    {
     "title": "Bytes out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(raft_transport_message_size_sum[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Append entries per message",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "raft_transport_append_entries > 0",
       "legendFormat": "{{job}} {{quantile}}"
      }
     ]
    },
    {
     "title": "Append entries per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(raft_transport_append_entries_sum[$__rate_interval]) ",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Duplicate append entries sent per message",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "raft_transport_duplicate_append_entries > 0",
       "legendFormat": "{{job}}->{{receiver}} {{quantile}}"
      }
     ]
    },
    {
     "title": "Duplicate append entries per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(raft_transport_duplicate_append_entries_sum[$__rate_interval]) > 0",
       "legendFormat": "{{job}}->{{receiver}}"
      }
     ]
    },
    { "title": "Panel Title", "type": "add-panel", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 } }
   ]
  },
  { "title": "Raft storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Operations per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(node_raft_operation_sum[$__rate_interval]) / rate(node_raft_operation_count[$__rate_interval]) ",
     "legendFormat": "{{job}} {{operation}}"
    }
   ]
  },
  {
   "title": "Operation durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_raft_operation",
     "legendFormat": "{{job}} {{operation}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Block loading duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "raft_storage_block_loaded", "legendFormat": "{{job}} {{quantile}}" }
   ]
  },
  {
   "title": "Block loads per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(raft_storage_block_loaded_count[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average entry size written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(rate(raft_storage_bytes_written_sum[$__rate_interval]) / rate(raft_storage_bytes_written_count[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Bytes written per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(raft_storage_bytes_written_sum[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Bytes read per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(raft_storage_bytes_read_sum[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Go internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Go routines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "last_over_time(go_goroutines[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    { "expr": "go_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "GCs per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[$__rate_interval]) / rate(go_gc_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Max GC pause duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{job}} {{quantile}}" }
   ]
  },
  {
   "title": "Used memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "Used {{job}}" },
    { "expr": "go_memstats_sys_bytes", "legendFormat": "System {{job}}" }
   ]
  },
  {
   "title": "Bytes allocated per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}