global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'kv-1'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 2s

    static_configs:
      - targets: ['host.docker.internal:8001']

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'kv-2'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 2s

    static_configs:
      - targets: ['host.docker.internal:8002']
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'kv-3'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 2s

    static_configs:
      - targets: ['host.docker.internal:8003']